/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiOrganizeTranscriptRouteImport } from './routes/api/organize-transcript'
import { Route as ApiPublicTokenRouteImport } from './routes/api/public/token'

const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizeTranscriptRoute = ApiOrganizeTranscriptRouteImport.update({
  id: '/api/organize-transcript',
  path: '/api/organize-transcript',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTokenRoute = ApiPublicTokenRouteImport.update({
  id: '/api/public/token',
  path: '/api/public/token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/api/organize-transcript': typeof ApiOrganizeTranscriptRoute
  '/api/public/token': typeof ApiPublicTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/api/organize-transcript': typeof ApiOrganizeTranscriptRoute
  '/api/public/token': typeof ApiPublicTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/api/organize-transcript': typeof ApiOrganizeTranscriptRoute
  '/api/public/token': typeof ApiPublicTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/embed' | '/api/organize-transcript' | '/api/public/token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/embed' | '/api/organize-transcript' | '/api/public/token'
  id:
    | '__root__'
    | '/'
    | '/embed'
    | '/api/organize-transcript'
    | '/api/public/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmbedRoute: typeof EmbedRoute
  ApiOrganizeTranscriptRoute: typeof ApiOrganizeTranscriptRoute
  ApiPublicTokenRoute: typeof ApiPublicTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organize-transcript': {
      id: '/api/organize-transcript'
      path: '/api/organize-transcript'
      fullPath: '/api/organize-transcript'
      preLoaderRoute: typeof ApiOrganizeTranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/token': {
      id: '/api/public/token'
      path: '/api/public/token'
      fullPath: '/api/public/token'
      preLoaderRoute: typeof ApiPublicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmbedRoute: EmbedRoute,
  ApiOrganizeTranscriptRoute: ApiOrganizeTranscriptRoute,
  ApiPublicTokenRoute: ApiPublicTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
